### PR TITLE
Getting the SD handle of an existing file directly from FILE_INDEX array

### PR DESCRIPTION
**Pull request by bochaco**
The function getSDHandle is requesting to the network to return the SD handle of an exiting file, when it can just retrieve it from its FILE_INDEX array.
I wasn't able to test it extensively due to some errors I get when I run the app locally, and which I believe are all related to a [safe-js bug](https://github.com/joshuef/safe-js/issues/21).

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @ustulation (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by frabrunelle** [comment]
> when it can just retrieve it from its FILE_INDEX array

The dataID handles stored in the FILE_INDEX object will only be valid as long as SAFE Launcher is running. If you restart SAFE Launcher they won't be valid anymore. These dataID handles are not used anymore in the code, so we should probably remove them.

**Comment by bochaco** [comment]
I see your point, I didn't consider to cover that scenario, although it wouldn't work either since the app doesn't refresh the authorization, so code to cover that would also be needed, right?

**Comment by frabrunelle** [comment]
> it wouldn't work either since the app doesn't refresh the authorization

I was more thinking of the scenario where you restart both SAFE Launcher and SAFE Browser. If you just restart SAFE Launcher, then I guess you would need to refresh the webpage. I don't think any additional code would be needed.

**Pull request closed without merging**
