### PR TITLE
MAID-1465 DNS and NFS functions

### PR DESCRIPTION
**Pull request by krishnaIndia**
implementation with the logger initialisation in main.js

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_examples/13)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
<sup>**[dns_example/src/scripts/safe_api/nfs.js, line 33 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_examples/13#-K1YtPGrZ6imd49B8QD-)** ([raw file](https://github.com/maidsafe/safe_examples/blob/06f051bb25636098af14498569f5fb67e953ac02/dns_example/src/scripts/safe_api/nfs.js#L33)):</sup>
`"endpoint": "safe-api/v1.0/nfs/modify-file"` is for modify-file and logging a create directory? not sure what this UploadData function is intended for here. Is it to mutate a file/folder?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_examples/13)

**Comment by Viv-Rajkumar** [comment]
<sup>**[dns_example/src/scripts/safe_api/nfs.js, line 74 \[r1\]](https://reviewable.io:443/reviews/maidsafe/safe_examples/13#-K1Yttioop1PbIsaWYQx)** ([raw file](https://github.com/maidsafe/safe_examples/blob/06f051bb25636098af14498569f5fb67e953ac02/dns_example/src/scripts/safe_api/nfs.js#L74)):</sup>
invalid end-point?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_examples/13)

**Comment by Viv-Rajkumar** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_examples/13)

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_examples/13)

**Pull request merged**
