### PR TITLE
MAID-2622: refactor/playground: Change naming in snippet to be consis…

### PR DESCRIPTION
**Pull request by hunterlester**
…tent with safe_app_nodejs and web API

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by bochaco** [comment]
Let's delay this until we have a new formal release of safe_app_nodejs package.

**Comment by bochaco** [comment]
@hunterlester is it right this is obsolete due to PR #385 ?

**Comment by hunterlester** [comment]
@bochaco The minor change that is still relevant with this PR is using `delete` instead of `remove`.

**Comment by bochaco** [comment]
Ok, I see, then this PR should go against the `playground3-0`

**Comment by hunterlester** [comment]
@bochaco I'll need a different PR for [playground3-0](https://github.com/maidsafe/safe_examples/blob/playground3-0/safe_web_api_playground/static/js/code-snippets/mutableDataMutation.js#L16).

**Comment by bochaco** [comment]
@hunterlester , ok, so I guess you are assuming we are releasing a new version of Beaker with latest safe_app_nodejs, we'll need to decide if we are gonna be doing that or not.

**Comment by hunterlester** [comment]
@bochaco Right, good point. Here's a separate PR, https://github.com/maidsafe/safe_examples/pull/386, for 3.0.

**Comment by hunterlester** [comment]
Obsolete PR. Closing.

**Pull request closed without merging**
